### ISSUE TITLE
Build Guide

### ISSUE THREAD

**Issue by rafaeldelboni** [sadekbaroudi/barobord#1]
Hey hello, thanks for your work in this, the keyboard looks amazing and I'm planning to build a barobord (MX) myself and I have some questions :)

- Do you have a BOM (Bill of Materials)?
- I can use the Gerber.zip in the MX file or do you recommend generating it again? 
- Do you have a top switchplate variation with the cuts for the encoders and the OLED?

**Comment by sadekbaroudi** [comment]
Hi @rafaeldelboni - I'm glad you'll be building this! Please share pictures of your build. You can submit a pull request to put in the images directory and readme.md

* I can add a BOM for a build guide, sure. I'll keep this issue open until I do that. Note that if you use JLCPCB, I have generated the necessary BOM and POS files. You can use these files directly in the SMT assembly service ( https://github.com/sadekbaroudi/barobord/blob/master/mx/gerbers/barobord-bom.csv and https://github.com/sadekbaroudi/barobord/blob/master/mx/gerbers/barobord-bottom-pos.csv )
* I am pretty sure I updated it. I generate updated gerbers every time I make changes. But if you want to be safe, feel free to generate again.
* You can see I have stls for all variations here: https://github.com/sadekbaroudi/barobord/tree/master/cases/sandwich

**Comment by sadekbaroudi** [comment]
@rafaeldelboni 

Also, if you look at the last column in the bom csv link above, you'll see LSCS. You can use that part number to look up the parts on https://lcsc.com/

That will tell you all the components you need.

In addition to that, you'll just need M2 spacers (I think 8mm, maybe it's 10mm) and screws (4-6mm should be fine) to assemble the case. The rest is all in that csv.

**Comment by sadekbaroudi** [comment]
Added build guide in this commit:
https://github.com/sadekbaroudi/barobord/commit/c60ef5b02c841b090c1f3999e4f607ca9856b418

**Comment by rafaeldelboni** [comment]
I will start to build this soon, thanks for all your work on this.

**Comment by sadekbaroudi** [comment]
@rafaeldelboni - did you ever build this? Would love to see pictures!

**Comment by rafaeldelboni** [comment]
Hey @sadekbaroudi, I will build one this year haha, thanks for the reminder, I will start to get the parts.
My Torn is still working beautifully, but I want to try something new :) 
Hope you doing great :D

**Comment by sadekbaroudi** [comment]
@rafaeldelboni Nice! Enjoy! As always, let me know if you have any questions.
